import abc
import collections
import doctest
import functools
import inspect
import re
import string
import types
import typing
from collections.abc import Callable, Mapping, MutableMapping

from effectful.ops.types import Operation


class Tool[**P, T](Operation[P, T]):
    """A `Tool` is a function that may be called by a `Template`.

    A `Tool` wraps a normal Python callable; its signature (parameter types
    and return type) and docstring define the schema the model sees, and the
    model invokes it by name with JSON arguments.

    ## Example usage

    Templates may call any tool that is in their lexical scope. In the
    following example, the LLM suggests a vacation destination using the
    `cities` and `weather` tools:

    ```python
    @Tool.define
    def cities() -> list[str]:
        \"\"\"Return a list of cities that can be passed to `weather`.\"\"\"
        return ["Chicago", "New York", "Barcelona"]

    @Tool.define
    def weather(city: str) -> str:
        \"\"\"Given a city name, return a description of the weather in that city.\"\"\"
        status = {"Chicago": "cold", "New York": "wet", "Barcelona": "sunny"}
        return status.get(city, "unknown")

    @Template.define  # cities and weather auto-captured from lexical scope
    def vacation() -> str:
        \"\"\"Use the `cities` and `weather` tools to suggest a city that has good weather.\"\"\"
        raise NotHandled
    ```

    Class methods may be used as templates, in which case any other methods
    decorated with `Tool.define` will be provided as tools.

    """

    def __init__(self, default: Callable[P, T], name: str | None = None):
        if not default.__doc__:
            raise ValueError("Tools must have docstrings.")
        super().__init__(default, name=name)

    @classmethod
    def define(cls, *args, **kwargs) -> "Tool[P, T]":
        """Define a tool.

        See `effectful.ops.types.Operation.define` for more information on the
        use of `Tool.define`.

        """
        return typing.cast("Tool[P, T]", super().define(*args, **kwargs))


class FinalTool[**P, T](Tool[P, T]):
    """A `Tool` whose invocation *finalizes* a `Template` call.

    During completion a `Template` lets the LLM freely call any tool in
    scope, feeding each tool's result back for another turn.  When the LLM
    instead calls a `FinalTool`, that tool's return value becomes the
    Template's result and the completion loop terminates -- no further model
    turn is taken, so the value is attributed to executing the tool rather than
    generated by the model.

    This is the mechanism behind code-synthesis completion (see
    `effectful.handlers.llm.completions.SynthesizeAndCall`): the LLM
    "answers" by calling a final tool with a function it wrote, the harness
    applies that function to the original inputs, and the resulting value is the
    answer.

    A finalizing call that *fails* does not terminate the loop -- the error is
    fed back as a tool message and the model is given another turn (see
    `effectful.handlers.llm.completions.RetryLLMHandler`).
    """

    @classmethod
    def define(cls, *args, **kwargs) -> "FinalTool[P, T]":
        """Define a final tool.

        See `effectful.ops.types.Operation.define` for more information on
        the use of `FinalTool.define`.
        """
        return typing.cast("FinalTool[P, T]", super().define(*args, **kwargs))


class Template[**P, T](Tool[P, T]):
    """A `Template` is a function that is implemented by a large language model.

    ## Constructing Templates

    Apply `Template.define` as a decorator to a fully type-annotated function or
    method whose body is `raise NotHandled`. The docstring is a
    [format string](https://docs.python.org/3/library/string.html#format-string-syntax)
    prompt: its `{...}` fields are filled at call time (see *Prompt assembly*
    below) and the LLM's response is decoded to the return type.

    `Template.define` validates the definition and raises if:

    - the function has no docstring (every `Tool` needs one);
    - a `{...}` field names something that is neither a parameter nor a name in
      lexical scope — every field must resolve at call time;
    - a doctest example (`>>>`) in the docstring contains an active `{...}` field:
      doctests must be constant, since the whole docstring is formatted into the
      prompt at call time; escape any literal braces as `{{` and `}}`.

    See `effectful.ops.types.Operation.define` for more on `Template.define`.

    The following template writes limericks on a given theme:

    >>> @Template.define
    ... def limerick(theme: str) -> str:
    ...     \"\"\"Write a limerick on the theme of {theme}. Do not use any tools.\"\"\"
    ...     raise NotHandled

    ## Structured output

    Templates may return types that are not strings.
    The output from the LLM is then decoded before being returned to the user.

    For example, this template returns integers:

    >>> @Template.define
    ... def primes(first_digit: int) -> int:
    ...     \"\"\"Give a prime number with {first_digit} as the first digit. Do not use any tools.\"\"\"
    ...     raise NotHandled

    Structured generation is used to constrain the LLM to return values that can be decoded without error.

    Templates can return complex data structures, such as dataclasses:

    >>> import dataclasses
    >>> @dataclasses.dataclass
    ... class KnockKnockJoke:
    ...     whos_there: str
    ...     punchline: str

    >>> @Template.define
    ... def write_joke(theme: str) -> KnockKnockJoke:
    ...     \"\"\"Write a knock-knock joke on the theme of {theme}. Do not use any tools.\"\"\"
    ...     raise NotHandled

    Many common Python data types are decodable without additional effort.
    To register a decoder for a custom type, see `effectful.handlers.llm.encoding.type_to_encodable_type`.

    ## Using tools

    Instances of `Tool` in a `Template`'s lexical scope may be called by the LLM
    during completion, and are offered automatically. Scope follows ordinary
    Python rules: enclosing-function locals, module globals, and — for a method
    template — sibling `Tool`/`Template` methods on the same class. A template
    cannot call a tool it cannot lexically see, so it should use only tools that
    are in scope and relevant to the task. Templates are themselves tools,
    enabling composition into agent workflows.

    ## Prompt assembly

    A call produces two messages. The **system message** is assembled once per
    conversation, ordered most-constant-first so it caches well. Each section is a
    top-level `#` heading whose contents nest beneath it; in order:

    | # | Section heading | Content | Constant over |
    | - | --------------- | ------- | ------------- |
    | 1 | `# The effectful LLM framework` | Framework concepts — the package overview plus a `##` subsection per concept (`Template`, `Tool`, `Agent`, `Encodable`, and any handler tool blocks), sourced from these docstrings | the process |
    | 2 | `# Module <name>` | Source of the template's module (docstring if source is unavailable) | the module |
    | 3 | `# Agent <cls>` (or `# Template`) | Agent docstring, then a `## <name><signature>` spec — prompt with `{...}` holes intact and argument JSON schemas — for every template sharing the instance's history (an `Agent`'s methods, or just this template) | the instance |
    | 4 | `# Imported modules` | Table of in-scope imports (name → module) | the scope |
    | 5 | `# Lexical scope` | Table of other in-scope bindings (name → type) | the scope |

    The **user message** is the per-call part — only its changing values are
    re-sent each turn; everything constant lives in the system message above. It
    has two parts:

    | # | Part | Content |
    | - | ---- | ------- |
    | 1 | Header | `<name><signature>` — identifies which template this turn calls |
    | 2 | Body | The docstring with each `{...}` hole replaced by the encoded value of that argument or in-scope name (non-text values, such as images, as separate content blocks) |

    """

    __context__: collections.ChainMap[str, typing.Any]

    @classmethod
    def _validate_doctests_constant(cls, template: "Template", doc: str) -> None:
        """Validate that no format string variables are spliced into doctests.

        The whole docstring is ``str.format``-ed into the prompt at call time,
        so an active replacement field inside a ``>>>`` example would be
        substituted, breaking the example. Doctests must therefore be constant:
        the example source, expected output and exception message may contain
        only escaped braces (``{{``/``}}``), never active fields.

        :raises TypeError: If any doctest example contains an active field.
        """
        try:
            parts = doctest.DocTestParser().parse(doc, template.__name__)
        except ValueError:
            # Malformed doctest -- not a prompt-field concern; it surfaces when
            # the doctests are actually run, so skip the constancy check here.
            return

        formatter = string.Formatter()
        spliced: list[str] = []
        for part in parts:
            if not isinstance(part, doctest.Example):
                continue
            for text in (part.source, part.want, part.exc_msg or ""):
                try:
                    spliced.extend(
                        field_name
                        for _, field_name, _, _ in formatter.parse(text)
                        if field_name is not None
                    )
                except ValueError:
                    # An unbalanced brace (e.g. a bare ``{`` or ``}``) is also
                    # non-constant: ``str.format`` would reject it at call time.
                    spliced.append("<unbalanced brace>")

        if spliced:
            # Render the auto-numbered empty field ``{}`` readably.
            shown = sorted({f or "{}" for f in spliced})
            raise TypeError(
                f"Template '{template.__name__}' splices {shown} "
                f"into a doctest example. Doctests must be constant -- they are "
                f"formatted into the prompt at call time, so they may not contain "
                f"format fields. Escape literal braces as '{{{{' and '}}}}'."
            )

    @classmethod
    def _validate_prompt(
        cls,
        template: "Template",
        context: collections.ChainMap[str, typing.Any],
    ) -> None:
        """Validate that all format string variables in the docstring
        refer to names resolvable at call time.

        Each variable must be either a parameter in the signature
        or a name captured in the lexical context. Additionally, doctest
        examples in the docstring must be constant (see
        :meth:`_validate_doctests_constant`).

        :raises TypeError: If any format string variable cannot be resolved, or
            a format field is spliced into a doctest example.
        """
        assert template.__doc__ is not None
        doc = template.__doc__
        cls._validate_doctests_constant(template, doc)
        formatter = string.Formatter()
        param_names = set(template.__signature__.parameters.keys())
        context_keys = set(context.keys())
        allowed_names = param_names | context_keys

        unresolved: list[str] = []
        for _, field_name, _, _ in formatter.parse(doc):
            if field_name is None:
                continue
            # Extract root identifier from compound names like
            match = re.match(r"^(\w+)", field_name)
            root = match.group(1) if match else field_name
            if root not in allowed_names:
                unresolved.append(field_name)

        if unresolved:
            raise TypeError(
                f"Template '{template.__name__}' docstring references undefined "
                f"variables {list(sorted(unresolved))} that are not in the signature "
                f"{{{template.__signature__}}} or lexical scope."
            )

    def __get__[S](self, instance: S | None, owner: type[S] | None = None):
        if hasattr(self, "_name_on_instance") and hasattr(
            instance, self._name_on_instance
        ):
            return getattr(instance, self._name_on_instance)

        result = super().__get__(instance, owner)
        self_param_name = list(self.__signature__.parameters.keys())[0]
        result.__context__ = self.__context__.new_child({self_param_name: instance})
        if isinstance(instance, Agent):
            assert isinstance(result, Template) and not hasattr(result, "__history__")
            result.__history__ = instance.__history__  # type: ignore[attr-defined]
        return result

    @classmethod
    def define[**Q, V](
        cls, default: Callable[Q, V], *args, **kwargs
    ) -> "Template[Q, V]":
        """Define a prompt template.

        `define` takes a function and can be used as a decorator.
        The function's docstring should be a prompt, which may be templated in the function arguments.
        The prompt will be provided with any instances of `Tool` that exist in the lexical context as callable tools.

        See `effectful.ops.types.Operation.define` for more information on the use of `Template.define`.

        """
        frame = inspect.currentframe()
        assert frame is not None
        frame = frame.f_back
        assert frame is not None

        # Skip class body frames: in Python, class bodies are not lexical
        # scopes for methods, so their locals should not be captured.
        qualname = frame.f_locals.get("__qualname__")
        if qualname is not None:
            for name in reversed(qualname.split(".")):
                if name == "<locals>":
                    break
                assert frame is not None
                frame = frame.f_back

        # Use the qualname of the decorated function to identify which
        # frames are *lexical* enclosers (as opposed to dynamic callers).
        # A segment preceding "<locals>" in the qualname is an enclosing
        # function; everything else (class names, the function itself) is not.
        assert frame is not None
        _fn = default
        if isinstance(_fn, staticmethod | classmethod):
            _fn = _fn.__func__
        parts = _fn.__qualname__.split(".")
        enclosing_fns = [
            parts[i] for i in range(len(parts) - 1) if parts[i + 1] == "<locals>"
        ]
        enclosing_fns.reverse()  # innermost first for frame walking

        globals_proxy: types.MappingProxyType[str, typing.Any] = types.MappingProxyType(
            frame.f_globals
        )
        contexts: list[types.MappingProxyType[str, typing.Any]] = []
        for fn_name in enclosing_fns:
            while frame is not None and frame.f_locals is not frame.f_globals:
                if frame.f_code.co_name == fn_name:
                    contexts.append(types.MappingProxyType(frame.f_locals))
                    frame = frame.f_back
                    break
                frame = frame.f_back
        contexts.append(globals_proxy)
        context: collections.ChainMap[str, typing.Any] = collections.ChainMap(
            *typing.cast(list[MutableMapping[str, typing.Any]], contexts)
        )
        op = super().define(default, *args, **kwargs)
        op.__context__ = context  # type: ignore[attr-defined]
        # Keep validation on original define-time callables, but skip the bound wrapper path.
        # to avoid dropping `self` from the signature and falsely rejecting valid prompt fields like `{self.name}`.
        is_bound_wrapper = (
            isinstance(default, types.MethodType) and default.__self__ is not None
        )
        if not isinstance(op, staticmethod | classmethod) and not is_bound_wrapper:
            cls._validate_prompt(typing.cast(Template, op), context)

        return typing.cast(Template[Q, V], op)


class Agent(abc.ABC):
    """Mixin that gives each instance a persistent LLM message history.

    Subclass and decorate methods with `Template.define`.
    Each instance accumulates messages across calls so the LLM sees
    prior conversation context.

    Agents compose freely with `dataclasses.dataclass` and other
    base classes.  Instance attributes are available in template
    docstrings via `{self.attr}`.

    Example:

    ```python
    import dataclasses
    from effectful.handlers.llm import Agent, Template
    from effectful.handlers.llm.completions import LiteLLMProvider
    from effectful.ops.semantics import handler
    from effectful.ops.types import NotHandled

    @dataclasses.dataclass
    class ChatBot(Agent):
        bot_name: str = dataclasses.field(default="ChatBot")

        @Template.define
        def send(self, user_input: str) -> str:
            \"""Friendly bot named {self.bot_name}. User writes: {user_input}\"""
            raise NotHandled

    provider = LiteLLMProvider()
    chatbot = ChatBot()

    with handler(provider):
        chatbot.send("Hi! How are you? I am in France.")
        chatbot.send("Remind me again, where am I?")  # sees prior context
    ```

    ## Encapsulation via lexical scope

    Since scope is ordinary Python scope, defining agents inside a function
    partitions their `Template`s and `Tool`s into disjoint sets:

    ```python
    class Chatbot(Agent):
        @Template.define
        def respond(self, user_query: str) -> str: ...

    class TravelAdvisor(Agent):
        @Template.define
        def recommend(self, user_query: str) -> str: ...
        @Tool.define
        def search_weather(self, city: str) -> str: ...

    def main():
        chatbot, advisor = Chatbot(), TravelAdvisor()

        @Template.define
        def simulate(chatbot, advisor) -> str:
            \"""Use {chatbot} and {advisor} to simulate a conversation.\"""
            ...
    ```

    `chatbot.respond` sees only its own methods (plus module-level definitions),
    not `advisor`'s; `simulate` sees `chatbot` and `advisor`, but they cannot see
    `simulate`. Inlining these definitions into module scope instead would let
    every template see every other. Agents that need overlapping toolsets should
    share tools through a common base class or mixin rather than redefining them.

    """

    @functools.cached_property
    def __history__(self) -> collections.OrderedDict[str, Mapping[str, typing.Any]]:
        return collections.OrderedDict()
